# Site settings
title: AtomLinter
email: kepler+atomlinter@stickajones.org
url: https://atomlinter.github.io
description: Lint your code with ease in Atom.

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: efeae1
  secondary: 66595c
  active: 81c08b

# Footer settings
footer:
  copyright: 2015 Kepler Sticka-Jones

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - LICENCE
  - README.md
